---
title: "Wordcloud Exploration"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```


Referenced from http://www.sthda.com/english/wiki/text-mining-and-word-cloud-fundamentals-in-r-5-simple-steps-you-should-know

```{r}
library(tidyverse)
library(jsonlite)
library(stringr)
library(tm)
library(SnowballC)
library(wordcloud)
library(clusterSim)
library(webchem)
library(config)
```

```{r import_scripts}
source("lib/pubchem_parse.R", local = TRUE)
```

```{r}
cf <- config::get("dbconnection")
```

```{r}
db <- dbConnect(drv = "PostgreSQL",
                dbname   = cf$database,
                host     = cf$server,
                port     = cf$port,
                user     = cf$uid,
                password = cf$pwd)
```

```{r}
if (as.logical(dbGetQuery(db, paste("SELECT EXISTS(SELECT 1 FROM pubchem_text WHERE compound_id =", "6618", ');')))) {
  text.temp <- dbGetQuery(db, paste('SELECT * FROM pubchem_text',
                                  'WHERE compound_id = ', "6618", ';'))
  text.temp <- DBToDFRaw(text.temp)
} else {
  compound.temp <- PubChemScrape(chem.ids[[i]], db, db.bypass)
  text.temp <- dbGetQuery(db, paste('SELECT * FROM pubchem_text',
                                  'WHERE compound_id = ', "6618", ';'))
  text.temp <- DBToDFRaw(text.temp)
}
```


```{r}
temp <- paste(text.temp, collapse = " ")
```

```{r}
str_count(temp, "\\S+")
```


```{r}
temp_corpus <- Corpus(VectorSource(temp))
```

```{r}
toSpace <- content_transformer(function (x, pattern) gsub(pattern, " ", x))
temp_corpus <- tm_map(temp_corpus, content_transformer(tolower))
temp_corpus <- tm_map(temp_corpus, removeNumbers)
temp_corpus <- tm_map(temp_corpus, removeWords, stopwords("english"))
temp_corpus <- tm_map(temp_corpus, removePunctuation)
temp_corpus <- tm_map(temp_corpus, stripWhitespace)
```

```{r remove_words}
temp_corpus <- tm_map(temp_corpus, removeWords, c("approximately", "administered", "authors", "days", "dose", "fate", "following", "found", "group", "highest", "hours", "levels", "nature", "present", "respectively", "samples", "similar", "via"))
```



```{r}
dtm <- TermDocumentMatrix(temp_corpus)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
d <- data.frame(word = names(v), freq=v)
```

```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1, max.words = 200, random.order = FALSE, rot.per = 0.35, colors = brewer.pal(8, "Dark2"))
```


```{r}
dbDisconnect(db)
```

