---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("knitr")
install.packages("RCurl")
install.packages("rjson")
install.packages("rvest")
```


```{r knitr, echo=FALSE}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r library, echo=FALSE}
library(RCurl)
library(rjson)
library(rvest)
```

Most – if not all – of the information the service needs to produce its results is encoded into the URL. The general form of the URL has three parts – input, operation, and output – after the common prefix, followed by operation options as URL arguments (after the ‘?’):

https://pubchem.ncbi.nlm.nih.gov/rest/pug/<input specification>/<operation specification>/[<output specification>][?<operation_options>]


```{r tbbpa_json}
tbbpa <- fromJSON(getURL(url = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/6618/JSON"))
```

```{r tbbpa_txt}
tbbpa_txt <- getURL("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/6618/TXT")
```

```{r}
guess_encoding("https://pubchem.ncbi.nlm.gov/compound/6618")
```


```{r tbbpa_rvest}
tbbpa_rvest <- read_html("https://pubchem.ncbi.nlm.nih.gov/compound/6618", encoding = "UTF-8")
tbbpa_data <-  html_nodes(tbbpa_rvest, "#Absorption-Distribution-and-Excretion")
tbbpa_data <-  html_nodes(tbbpa_data, ".section-content-item:nth-child(1)")
tbbpa_data <-  html_text(tbbpa_data)
```

