DFRawToDB <- function(df) {
  names(df) <- c( `compound.id` = "compound_id",
                  `Pharmacology.text` = "pharmacology_text",
                  `Absorption, Distribution and Excretion` = "absorption_distribution_excretion_text",
                  `Metabolism/Metabolites.text` = "metabolism_metabolites_text",
                  `Biological Half-Life.text` = "biological_half_life_text",
                  `Mechanism of Action.text` = "mechanism_of_action_text",
                  `Methods of Manufacturing.text` = "methods_of_manufacturing_text",
                  `Consumption.text` = "consumption_text",
                  `Analytic Laboratory Methods.text` = "analytic_lab_methods_text",
                  `Clinical Laboratory Methods.text` = "clinical_lab_methods_text",
                  `Hazards Identification.text` = "hazards_identification_text",
                  `Safety and Hazard Properties.text` = "safety_hazards_prop_text",
                  `First Aid Measures.text` = "first_aid_measures_text",
                  `Fire Fighting Measures.text` = "fire_fighting_measures_text",
                  `Accidental Release Measures.text` = "accidental_release_measures_text",
                  `Handling and Storage.text` = "handling_storage_text",
                  `Exposure Control and Personal Protection.text` = "exposure_control_and_pp_text",
                  `Stability and Reactivity.text` = "stability_reactivity_text",
                  `Transport Information.text` = "transport_info_text",
                  `Regulatory Information.text` = "regulatory_info_text",
                  `Toxicological Information.text` = "tox_info_text",
                  `Ecological Information.text` = "eco_info_text")

  return(df)
}

DFCountsToDB <- function(df) {
  names(df) <- c( `compound.id` = "compound_id",
                  `name.info` = "name_info",
                  `Pharmacology and Biochemistry` = "pharmacology_and_biochemistry",
                  `Pharmacology` = "pharmacology",
                  `Absorption, Distribution and Excretion` = "absoprption_distribution_excretion",
                  `Metabolism/Metabolites` = "metabolism_metabolites",
                  `Biological Half-Life` = "biological_half_life",
                  `Mechanism of Action` = "mechanism_of_action",
                  `Use and Manufacturing` = "use_and_manufacturing",
                  `Methods of Manufacturing` = "methods_of_manufacturing",
                  `Consumption` = "consumption",
                  `Identification` = "identification",
                  `Analytic Laboratory Methods` = "analytic_lab_methods",
                  `Clinical Laboratory Methods` = "clinical_lab_methods",
                  `Safety and Hazards` = "safety_hazards",
                  `Hazards Identification` = "hazards_identification",
                  `Safety and Hazard Properties` = "safety_hazards_prop",
                  `First Aid Measures` = "first_aid_measures",
                  `Fire Fighting Measures` = "fire_fighting_measures",
                  `Accidental Release Measures` = "accidental_release_measures",
                  `Handling and Storage` = "handling_storage",
                  `Exposure Control and Personal Protection` = "exposure_control_and_pp",
                  `Stability and Reactivity` = "stability_reactivity",
                  `Transport Information` = "transport_info",
                  `Regulatory Information` = "regulatory_info",
                  `Toxicity` = "toxicity",
                  `Toxicological Information` = "tox_info",
                  `Ecological Information` = "eco_info",
                  `Literature` = "literature",
                  `PubMed Citations` = "pubmed_citations",
                  `Metabolite References` = "metabolite_references",
                  `Springer Nature References` = "nature_references",
                  `Biomolecular Interactions and Pathways` = "bio_interactions_pathways",
                  `Biosystems and Pathways` = "biosystems_pathways")

  return(df)
}

DBToDFRaw <- function(df) {
  names(df) <- c( `compound_id` = "compound.id",
                  `pharmacology_text` = "Pharmacology.text",
                  `absorption_distribution_excretion_text` = "Absorption, Distribution and Excretion.text",
                  `metabolism_metabolites_text` = "Metabolism/Metabolites.text",
                  `biological_half_life_text` = "Biological Half-Life.text",
                  `mechanism_of_action_text` = "Mechanism of Action.text",
                  `methods_of_manufacturing_text` = "Methods of Manufacturing.text",
                  `consumption_text` = "Consumption.text",
                  `analytic_lab_methods_text` = "Analytic Laboratory Methods.text",
                  `clinical_lab_methods_text` = "Clinical Laboratory Methods.text",
                  `hazards_identification_text` = "Hazards Identification.text",
                  `safety_hazards_prop_text` = "Safety and Hazard Properties.text",
                  `first_aid_measures_text` = "First Aid Measures.text",
                  `fire_fighting_measures_text` = "Fire Fighting Measures.text",
                  `accidental_release_measures_text` = "Accidental Release Measures.text",
                  `handling_storage_text` = "Handling and Storage.text",
                  `exposure_control_and_pp_text` = "Exposure Control and Personal Protection.text",
                  `stability_reactivity_text` = "Stability and Reactivity.text",
                  `transport_info_text` = "Transport Information.text",
                  `regulatory_info_text` = "Regulatory Information.text",
                  `tox_info_text` = "Toxicological Information.text",
                  `eco_info_text` = "Ecological Information.text")

  return(df)
}

DBToDFCounts <- function(df) {
  names(df) <- c( `compound_id` = "compound.id",
                  `name_info` = "name.info",
                  `pharmacology_and_biochemistry` = "Pharmacology and Biochemistry",
                  `pharmacology` = "Pharmacology",
                  `absoprption_distribution_excretion` = "Absorption, Distribution and Excretion",
                  `metabolism_metabolites` = "Metabolism/Metabolites",
                  `biological_half_life` = "Biological Half-Life",
                  `mechanism_of_action` = "Mechanism of Action",
                  `use_and_manufacturing` = "Use and Manufacturing",
                  `methods_of_manufacturing` = "Methods of Manufacturing",
                  `consumption` = "Consumption",
                  `identification` = "Identification",
                  `analytic_lab_methods` = "Analytic Laboratory Methods",
                  `clinical_lab_methods` = "Clinical Laboratory Methods",
                  `safety_hazards` = "Safety and Hazards",
                  `hazards_identification` = "Hazards Identification",
                  `safety_hazards_prop` = "Safety and Hazard Properties",
                  `first_aid_measures` = "First Aid Measures",
                  `fire_fighting_measures` = "Fire Fighting Measures",
                  `accidental_release_measures` = "Accidental Release Measures",
                  `handling_storage` = "Handling and Storage",
                  `exposure_control_and_pp` = "Exposure Control and Personal Protection",
                  `stability_reactivity` = "Stability and Reactivity",
                  `transport_info` = "Transport Information",
                  `regulatory_info` = "Regulatory Information",
                  `toxicity` = "Toxicity",
                  `tox_info` = "Toxicological Information",
                  `eco_info` = "Ecological Information",
                  `literature` = "Literature",
                  `pubmed_citations` = "PubMed Citations",
                  `metabolite_references` = "Metabolite References",
                  `nature_references` = "Springer Nature References",
                  `bio_interactions_pathways` = "Biomolecular Interactions and Pathways",
                  `biosystems_pathways` = "Biosystems and Pathways")

  return(df)
}
